import asyncio
import logging
import os
import tempfile
from datetime import datetime

from jinja2 import Template

from .celery_app import celery_app
from clusterspider.config import settings
from clusterspider.graph.driver import get_driver, close_driver
from clusterspider.graph.repository import GraphRepository
from clusterspider.graph.models import EntityType

logger = logging.getLogger(__name__)

REPORT_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>ClusterSpider Report - {{ title }}</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #333; }
        h1 { color: #1a1a2e; border-bottom: 2px solid #16213e; padding-bottom: 10px; }
        h2 { color: #16213e; margin-top: 30px; }
        .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }
        .stat-card { background: #f8f9fa; border-radius: 8px; padding: 15px; border-left: 4px solid #0f3460; }
        .stat-value { font-size: 24px; font-weight: bold; color: #0f3460; }
        .stat-label { font-size: 12px; color: #666; text-transform: uppercase; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f1f3f5; font-weight: 600; }
        .tag { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; margin: 2px; }
        .tag-domain { background: #dbeafe; color: #1e40af; }
        .tag-ip { background: #dcfce7; color: #166534; }
        .tag-email { background: #fef3c7; color: #92400e; }
        .tag-leak { background: #fee2e2; color: #991b1b; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <h1>ClusterSpider OSINT Report</h1>
    <p><strong>Target:</strong> {{ title }}</p>
    <p><strong>Generated:</strong> {{ generated_at }}</p>

    <h2>Statistics Summary</h2>
    <div class="stats">
        {% for label, count in stats.items() %}
        {% if label != '_relationships' %}
        <div class="stat-card">
            <div class="stat-value">{{ count }}</div>
            <div class="stat-label">{{ label }}</div>
        </div>
        {% endif %}
        {% endfor %}
    </div>

    {% if leaks %}
    <h2>Leak Records</h2>
    <table>
        <tr><th>Breach</th><th>Date</th><th>Data Classes</th></tr>
        {% for leak in leaks %}
        <tr>
            <td>{{ leak.breach_name }}</td>
            <td>{{ leak.breach_date or 'N/A' }}</td>
            <td>{{ leak.data_classes|join(', ') if leak.data_classes else 'N/A' }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if domains %}
    <h2>Discovered Domains / Subdomains</h2>
    <table>
        <tr><th>Domain</th><th>First Seen</th></tr>
        {% for d in domains %}
        <tr><td>{{ d.value }}</td><td>{{ d.first_seen or '' }}</td></tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if ips %}
    <h2>IP Addresses</h2>
    <table>
        <tr><th>IP</th><th>Country</th><th>City</th><th>ASN</th></tr>
        {% for ip in ips %}
        <tr>
            <td>{{ ip.value }}</td>
            <td>{{ ip.geo_country or '' }}</td>
            <td>{{ ip.geo_city or '' }}</td>
            <td>{{ ip.get('asn', '') }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    <div class="footer">
        Generated by ClusterSpider OSINT Platform &bull; {{ generated_at }}
    </div>
</body>
</html>
"""


@celery_app.task(bind=True, name="clusterspider.workers.report_tasks.generate_report")
def generate_report(self, user_id: str, target: str, target_type: str, format: str = "html"):
    return asyncio.run(_generate_report_async(user_id, target, target_type, format))


async def _generate_report_async(user_id: str, target: str, target_type: str, format: str):
    driver = await get_driver()
    repo = GraphRepository(driver)

    label = EntityType.DOMAIN if target_type == "domain" else EntityType.IP
    stats = await repo.get_stats(user_id)

    neighbors = await repo.get_neighbors(label, target, user_id, depth=2)
    nodes = neighbors.get("nodes", [])

    leaks = [n for n in nodes if n.get("_label") == "LeakRecord"]
    domains = [n for n in nodes if n.get("_label") == "Domain"]
    ips = [n for n in nodes if n.get("_label") == "IP"]

    await close_driver()

    template = Template(REPORT_HTML_TEMPLATE)
    html_content = template.render(
        title=target,
        generated_at=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        stats=stats,
        leaks=leaks,
        domains=domains,
        ips=ips,
    )

    reports_dir = os.path.join(tempfile.gettempdir(), "clusterspider_reports")
    os.makedirs(reports_dir, exist_ok=True)

    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

    if format == "pdf":
        try:
            from weasyprint import HTML
            pdf_path = os.path.join(reports_dir, f"report_{target}_{timestamp}.pdf")
            HTML(string=html_content).write_pdf(pdf_path)
            return {"format": "pdf", "path": pdf_path, "target": target}
        except ImportError:
            logger.warning("WeasyPrint not installed, falling back to HTML")
            format = "html"

    html_path = os.path.join(reports_dir, f"report_{target}_{timestamp}.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    return {"format": "html", "path": html_path, "target": target}
